### ISSUE TITLE
Content checklist on initial data

### ISSUE THREAD

**Issue by VesaJuvonen** [pnp/m365-extensibility-lookbook#1]
* [x] bot - Waldek
* [x] channel-group-tab - Waldek
* [x] incoming-webhook - Waldek
* [x] messaging-extension - Waldek
* [x] office-365-connector - Waldek
* [ ] office-addin-command - David
* [ ] office-content-addin - David
* [ ] office-contextual-addin - David
* [ ] office-custom-function - David
* [ ] office-dialog-box - David
* [ ] office-task-pane - David
* [ ] onedrive-file-handler - David
* [x] outgoing-webhook - Waldek
* [x] personal-tab - Waldek
* [x] power-apps-canvas-app - Hugo
* [x] power-apps-model-driven-app - Hugo
* [x] power-apps-portals - Hugo
* [x] power-apps-power-virtual-agents - Hugo
* [x] power-automate-approval-flow - Hugo
* [x] power-automate-automated-flow - Hugo
* [x] power-automate-business-process-flow - Hugo
* [x] power-automate-desktop-flow - Hugo
* [x] power-automate-instant-flow - Hugo
* [x] power-automate-scheduled-flow - Hugo
* [ ] professional-services-document-management - Vesa
* [ ] professional-services-project-finder - Vesa
* [ ] professional-services-time-expense - Vesa
* [ ] profile-card-properties - Graph Profile Card -  David
* [ ] spfx-application-customizer - Vesa
* [ ] spfx-field-customizer - Vesa
* [ ] spfx-list-view-command-set - Vesa
* [ ] spfx-search-query-extension - Vesa
* [ ] spfx-webpart - Vesa
* [x] task-module - Waldek
